"""Does an implementation that matches a rival reading at the corpus bound
still follow that reading past it?

    # 1. emit the probe (the alternative-carrying cases, asked for more)
    python3 conformance/reading_past_bound.py --emit-probe -o /tmp/probe.ndjson
    # 2. feed it to each adapter directly (NOT through score.py: the probe
    #    carries a longer `limit` than the corpus row does)
    python3 conformance/adapters/dateutil_adapter.py < /tmp/probe.ndjson > /tmp/du.jsonl
    # 3. judge
    python3 conformance/reading_past_bound.py --run dateutil=/tmp/du.jsonl ...

Why this exists
---------------
`score.py` does not call an answer wrong when it equals one of the case's
`reading_alternatives`; it books it as `fail_other_reading`, on the grounds
that the corpus knows the case has more than one defensible answer (findings
018 and 024). That excuse is granted on the evidence of a *bounded* list --
115 of the 1728 scored cases carry an alternative and 110 of them are cut at
eight occurrences by the corpus's own limit, not by the rule, which is open in
all 115.

Finding 060's standing rule 58 says agreement inside the corpus bound is not
agreement: two implementations doing entirely different things can produce the
same first eight occurrences and part at the ninth. That rule was derived from
cross-lineage agreement in the `fail` bucket. It was never turned back on the
corpus's own pass-granting mechanism, which is where it bites hardest: if a
match to a rival reading is an artifact of the bound, the corpus is excusing a
defect by name.

So this tool re-asks each alternative-carrying case at a longer limit and puts
the two lists side by side:

  holds        the adapter's longer answer equals the reading extended to the
               same length. The excuse survives; the implementation really is
               reading 3.3.10 the other way.
  breaks       the adapter matched the reading to the bound and then left it.
               The `fail_other_reading` booking was an artifact of the bound;
               the report gives the occurrence index where the two part.
  truncated    the adapter returned fewer occurrences than asked but agreed
               for as long as it ran. Its own window, not a disagreement
               (finding 056); charged to nobody.
  reference_exhausted
               the reading itself ran out before the probe limit and the
               adapter agreed with all of it. Untested past that point, and
               charged to nobody -- this is my horizon, not the adapter's.
  n/a          the adapter did not match any reading at the bound.

The extended readings are regenerated by `src/build_corpus._readings`, the
function that wrote them into the corpus, rather than by a local
reimplementation (standing rule 57). At the corpus's own n every one of the
115 comes back byte-identical, which is the check this tool runs first and
refuses to continue without.

What a `breaks` row does NOT establish: which side is right. It establishes
only that the corpus's stated reason for not counting the answer as a
mismatch -- "this is the other reading" -- does not describe what the
implementation does.
"""
import json, os, sys, argparse, collections
from datetime import datetime, timedelta

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "src"))
import build_corpus, naive  # noqa: E402

DEFAULT_CASES = os.path.join(REPO, "conformance", "cases.ndjson")

# How far past DTSTART the reference expander is allowed to look while
# regenerating a reading for this report. Three centuries is not a claim about
# calendars; it is simply enough that on every rule in this corpus the probe's
# `limit` is what ends the list rather than the window. `extend()` checks that.
WIDE = timedelta(days=365 * 300)


def _parse(s):
    s = s.rstrip("Z")
    return datetime.strptime(s, "%Y%m%dT%H%M%S" if "T" in s else "%Y%m%d")


def _fmt_pattern(dtstart):
    """A date-valued DTSTART must come back date-valued, as in the corpus."""
    return "%Y%m%dT%H%M%S" if "T" in dtstart else "%Y%m%d"


def alt_cases(path):
    """The scored cases that carry at least one rival reading."""
    out = []
    with open(path) as f:
        for line in f:
            c = json.loads(line)
            if c.get("reading_alternatives"):
                out.append(c)
    return out


def extend(case, limit):
    """(expect, readings) for this case regenerated at `limit` occurrences.

    The 30-year horizon is a property of my expander, not of the rule, and on a
    sparse `FREQ=YEARLY` rule it stops long before 25 occurrences -- so the
    readings are regenerated against a horizon wide enough that the *limit* is
    what ends the list. Without this the reference stops early, the adapter
    keeps going, and the difference looks like the implementation leaving the
    reading when it is only my instrument running out (standing rule 49; this
    is exactly what the first run of this tool reported, 11 times).

    Raises if the regeneration at the case's own length and the corpus's own
    horizon does not reproduce the corpus byte for byte -- a silent drift here
    would make every verdict below meaningless.
    """
    ds = _parse(case["dtstart"])
    pat = _fmt_pattern(case["dtstart"])
    n = len(case["expect"])
    at_n = [x.strftime(pat) for x in naive.expand(case["rrule"], ds, limit=n)][:n]
    if at_n != case["expect"] or \
            build_corpus._readings(case["rrule"], ds, n, at_n) != case["reading_alternatives"]:
        raise SystemExit("case %s does not regenerate; refusing to judge" % case["id"])
    horizon = ds + WIDE
    long = [x.strftime(pat) for x in
            naive.expand(case["rrule"], ds, horizon=horizon, limit=limit)][:limit]
    return long, build_corpus._readings(case["rrule"], ds, len(long), long, horizon)


def load_replies(path):
    """id -> occurrence list (or None when the adapter did not answer with one)."""
    out = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            occ = obj.get("occurrences")
            out[obj["id"]] = occ if isinstance(occ, list) else None
    return out


def _first_difference(a, b):
    for i, (x, y) in enumerate(zip(a, b)):
        if x != y:
            return i
    return min(len(a), len(b))


def judge(case, long_readings, got, limit):
    """Verdict for one adapter on one case. See the module docstring."""
    n = len(case["expect"])
    # An answer claims a reading when it agrees with the whole of it and ran at
    # least as far -- the probe asks for more occurrences than the corpus row
    # holds, so `got` is normally longer than the recorded list.
    #
    # The empty reading is excluded rather than matched. Eight corpus cases
    # record `dtstart_fill` as `[]` (the rewritten rule selects no date in any
    # Gregorian configuration -- finding 053), and an empty list has no past
    # the bound to test: every adapter agrees with all nothing of it. score.py
    # still books an adapter that returns nothing on those cases as
    # `fail_other_reading`; this tool simply cannot say whether that is right.
    matched = [name for name, occ in sorted(case["reading_alternatives"].items())
               if occ and got is not None and got[:n] == occ and len(got) >= n]
    if got is None or not matched:
        return ("n/a", None, None)
    name = matched[0]
    ext = long_readings.get(name)
    if ext is None:
        # The reading stopped being distinguishable from `expect` further out,
        # so there is no longer a rival list to follow. Not a break.
        return ("merged", name, None)
    if got == ext:
        return ("holds", name, None)
    if 0 < len(got) < len(ext) and ext[:len(got)] == got:
        return ("truncated", name, len(got))
    if len(got) > len(ext) and got[:len(ext)] == ext:
        # The *reference* ran out first and the adapter agreed with all of it.
        # Whatever the adapter did afterwards is untested, not wrong: nothing
        # here says the reading has no further occurrences (standing rule 49).
        return ("reference_exhausted", name, len(ext))
    return ("breaks", name, _first_difference(got, ext))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", default=DEFAULT_CASES)
    ap.add_argument("--limit", type=int, default=25,
                    help="occurrences to ask for; every case here is an open rule")
    ap.add_argument("--emit-probe", action="store_true")
    ap.add_argument("-o", "--out", default="-")
    ap.add_argument("--run", action="append", default=[], metavar="NAME=FILE")
    ap.add_argument("--json", help="write the full per-row report here")
    ap.add_argument("--show", type=int, default=20)
    a = ap.parse_args(argv)

    cases = alt_cases(a.cases)
    if a.emit_probe:
        f = sys.stdout if a.out == "-" else open(a.out, "w")
        for c in cases:
            f.write(json.dumps({"id": c["id"], "rrule": c["rrule"],
                                "dtstart": c["dtstart"], "limit": a.limit}) + "\n")
        if f is not sys.stdout:
            f.close()
            print("%d probe cases at limit %d -> %s" % (len(cases), a.limit, a.out))
        return 0

    if not a.run:
        raise SystemExit("give --emit-probe or at least one --run")
    runs = {}
    for spec in a.run:
        name, _, path = spec.partition("=")
        runs[name] = load_replies(path)

    long_by_id = {}
    for c in cases:
        long_by_id[c["id"]] = extend(c, a.limit)

    tally = collections.Counter()
    per_adapter = collections.defaultdict(collections.Counter)
    rows = []
    for c in cases:
        _long, long_readings = long_by_id[c["id"]]
        for name, replies in sorted(runs.items()):
            verdict, reading, idx = judge(c, long_readings, replies.get(c["id"]), a.limit)
            per_adapter[name][verdict] += 1
            if verdict == "n/a":
                continue
            tally[verdict] += 1
            rows.append({"id": c["id"], "adapter": name, "verdict": verdict,
                         "reading": reading, "diverges_at": idx,
                         "rrule": c["rrule"], "dtstart": c["dtstart"],
                         "bound": len(c["expect"]), "limit": a.limit,
                         "got": replies.get(c["id"]),
                         "reading_extended": long_readings.get(reading)})

    print("%d alternative-carrying cases, %d adapters, limit %d"
          % (len(cases), len(runs), a.limit))
    print("verdicts over the (case, adapter) pairs that matched a reading at the bound:")
    for k in ("holds", "breaks", "truncated", "merged", "reference_exhausted"):
        print("  %-10s %4d" % (k, tally[k]))
    print()
    for name in sorted(per_adapter):
        c = per_adapter[name]
        print("  %-9s holds %3d  breaks %3d  truncated %3d  merged %3d  "
              "ref-exhausted %3d  (no match %3d)"
              % (name, c["holds"], c["breaks"], c["truncated"], c["merged"],
                 c["reference_exhausted"], c["n/a"]))
    breaks = [r for r in rows if r["verdict"] == "breaks"]
    if breaks:
        print("\n%d BREAKS -- matched a reading to the bound, left it after:" % len(breaks))
        for r in breaks[:a.show]:
            print("  %s %-9s %-24s parts at occurrence %d (bound %d)"
                  % (r["id"], r["adapter"], r["reading"], r["diverges_at"], r["bound"]))
            print("      %s  DTSTART=%s" % (r["rrule"], r["dtstart"]))
    if a.json:
        json.dump({"limit": a.limit, "cases": len(cases),
                   "adapters": sorted(runs), "tally": dict(tally),
                   "per_adapter": {k: dict(v) for k, v in per_adapter.items()},
                   "rows": rows}, open(a.json, "w"), indent=1, sort_keys=True)
        print("\nfull report -> %s" % a.json)
    return 0


if __name__ == "__main__":
    sys.exit(main())
