"""RFC 5545 recurrence when DTSTART carries the DATE value type.

Everything else in this project assumes a DATE-TIME DTSTART. RFC 5545 also
allows DTSTART to be a DATE (sec. 3.8.2.4: "The default value type is DATE-TIME.
The value type can be set to a DATE value type."), which is what every all-day
event uses, and that case carries requirements of its own:

  sec. 3.3.10: "The BYSECOND, BYMINUTE and BYHOUR rule parts MUST NOT be
  specified when the associated "DTSTART" property has a DATE value type.
  These rule parts MUST be ignored in RECUR value that violate the above
  requirement (e.g., generated by applications that pre-date this revision of
  iCalendar)."

  sec. 3.3.10: "The value of the UNTIL rule part MUST have the same value type
  as the "DTSTART" property."

The first of those is unusual: a MUST NOT whose remedy is defined. A rule
carrying BYHOUR under a DATE-valued DTSTART is malformed *and* has a single
conformant expansion, obtained by dropping the offending parts. That makes it
checkable, and neither python-dateutil 2.9.0 nor rrule.js 2.8.1 does it -- see
findings/011-date-valued-dtstart.md.

Neither the sentence nor its remedy exists in RFC 2445; both are new in RFC
5545 (2009), which is what the parenthetical about applications that "pre-date
this revision" is referring to.

How the expected values here stay independent of any one implementation: a
DATE-valued expansion is the DATE-TIME expansion at midnight, of the rule with
the ignored parts removed, projected back onto dates. That reduction is exactly
the RFC sentence above, and it is recorded per case, so the *reduced* rule can
still be adjudicated by naive-vs-dateutil agreement the way every other case in
the corpus is. What this module adds on top of that is the reduction itself.
"""

from datetime import date, datetime, time, timedelta

import naive

#: Parts the RFC says MUST be ignored when DTSTART is DATE-valued.
TIME_PARTS = ("BYSECOND", "BYMINUTE", "BYHOUR")

#: FREQ values that address a unit finer than a day. RFC 5545 says nothing
#: about combining them with a DATE-valued DTSTART: sec. 3.3.10 restricts only
#: BYSECOND/BYMINUTE/BYHOUR, and no other section connects the value type to
#: FREQ (grepped, 2026-09-06). Rather than pick a reading, expansion refuses.
SUBDAILY = ("SECONDLY", "MINUTELY", "HOURLY")


class UndefinedForDateValue(Exception):
    """The RFC does not define this combination; no answer is invented."""


def parse_dtstart(text):
    """Parse a DTSTART value, returning (value, "DATE"|"DATE-TIME")."""
    if "T" in text:
        return datetime.strptime(text, "%Y%m%dT%H%M%S"), "DATE-TIME"
    return datetime.strptime(text, "%Y%m%d").date(), "DATE"


def fmt(value):
    """Format a date or datetime the way the corpus writes it."""
    if isinstance(value, datetime):
        return value.strftime("%Y%m%dT%H%M%S")
    return value.strftime("%Y%m%d")


def ignored_parts(rrule):
    """The parts of `rrule` a DATE-valued DTSTART requires be ignored."""
    present = {p.partition("=")[0].upper() for p in _body(rrule).split(";") if p}
    return [p for p in TIME_PARTS if p in present]


def until_violation(rrule):
    """UNTIL's value type against a DATE-valued DTSTART, or None if fine.

    sec. 3.3.10: "The value of the UNTIL rule part MUST have the same value
    type as the "DTSTART" property."
    """
    for part in _body(rrule).split(";"):
        k, _, v = part.partition("=")
        if k.upper() == "UNTIL" and ("T" in v.upper() or v.upper().endswith("Z")):
            return ("until-value-type", "UNTIL is a DATE-TIME but DTSTART is a "
                                        "DATE: %s" % part)
    return None


def reduce_rule(rrule):
    """The rule that a DATE-valued DTSTART actually expands, per sec. 3.3.10.

    Drops the parts the RFC says MUST be ignored, preserving the order of the
    rest, and leaves everything else -- including a malformed DATE-TIME UNTIL --
    alone, because the RFC defines a remedy only for the time parts.
    """
    kept = [p for p in _body(rrule).split(";")
            if p and p.partition("=")[0].upper() not in TIME_PARTS]
    return ";".join(kept)


def expand(rrule, dtstart, limit=1000, horizon=None):
    """Expand `rrule` from a DATE-valued `dtstart`, returning `date` objects."""
    if not isinstance(dtstart, date) or isinstance(dtstart, datetime):
        raise TypeError("dtstart must be a datetime.date, not a datetime")
    reduced = reduce_rule(rrule)
    freq = naive.parse(reduced)["FREQ"]
    if freq in SUBDAILY:
        raise UndefinedForDateValue(
            "FREQ=%s with a DATE-valued DTSTART: RFC 5545 does not say what a "
            "sub-daily recurrence of a date-valued start means" % freq)
    bad = until_violation(rrule)
    if bad:
        raise UndefinedForDateValue(bad[1])
    start = datetime.combine(dtstart, time(0, 0, 0))
    if horizon is not None:
        horizon = datetime.combine(horizon, time(0, 0, 0))
    occ = naive.expand(reduced, start, horizon=horizon, limit=limit)
    for x in occ:
        # A rule with no time parts cannot move the time of day off DTSTART's,
        # and DTSTART's is midnight by construction. If this ever fires, the
        # reduction above is wrong, not the assertion.
        assert x.time() == time(0, 0, 0), (rrule, x)
    return [x.date() for x in occ]


def _body(rrule):
    return rrule[6:] if rrule.upper().startswith("RRULE:") else rrule
