"""RFC 5545 section 3.6.5 VTIMEZONE: extract the spec's own examples, and resolve them.

Why this exists
---------------
Everything `rruleref` had tested about time zones so far took the zone as
given: `DTSTART;TZID=America/New_York` and let the tz database answer what the
offset was.  A `VTIMEZONE` component is the other case -- a calendar that
*carries its own transition rules* instead of naming a zone -- and it is the
one place in RFC 5545 where recurrence expansion is not merely scheduling but
the definition of what a wall-clock time means.  An error in a `VTIMEZONE`
`RRULE` silently moves every floating time in the calendar.

The rules implemented here are quoted, because getting them wrong is easy:

section 3.6.5, on how onsets are generated:

    "The 'DTSTART' and the 'TZOFFSETFROM' properties MUST be used when
     generating the onset DATE-TIME values (instances) from the 'RRULE'."

So an onset is a *wall-clock* value interpreted with the offset that was in
effect immediately **before** the change -- not with `TZOFFSETTO`, and not with
any IANA zone.  `19870405T020000` with `TZOFFSETFROM:-0500` is the instant
`1987-04-05T07:00:00Z`.

section 3.6.5, on `UNTIL`:

    "If observance is known to have an effective end date, the 'UNTIL'
     recurrence rule parameter MUST be used to specify the last valid onset of
     this observance (i.e., the UNTIL DATE-TIME will be equal to the last
     instance generated by the recurrence pattern).  It MUST be specified in
     UTC time."

That parenthesis is a checkable requirement, and `tests/test_vtimezone.py`
checks it against the RFC's own examples.

section 3.6.5, on `RDATE`:

    "'RDATE' in this usage MUST be specified as a date with local time value,
     relative to the UTC offset specified in the 'TZOFFSETFROM' property."

Same conversion as `DTSTART`.

Extraction, not transcription
-----------------------------
The five example components are read out of a sha256-pinned copy of the RFC by
program.  This repository has previously published a "quotation" from RFC 5545
that appears nowhere in it; RFC-derived data is never retyped here again.
"""

import os
import re
import sys
from datetime import datetime, timedelta, timezone

sys.path.insert(0, os.path.dirname(__file__))

from naive import expand as naive_expand
from rfc_worked_examples import read_rfc, RFC_PATH, RFC_SHA256, RFC_URL

SECTION_START = "3.6.5.  Time Zone Component"
SECTION_END = "3.6.6.  Alarm Component"

_PAGE_BREAK = re.compile(
    r"^(Desruisseaux .*\[Page \d+\]|RFC 5545 .*September 2009|\x0c)\s*$")


def section_lines(text, start=SECTION_START, end=SECTION_END):
    lines = text.split("\n")
    i = next(k for k, l in enumerate(lines) if l.startswith(start))
    j = next(k for k, l in enumerate(lines) if k > i and l.startswith(end))
    return [l for l in lines[i:j] if not _PAGE_BREAK.match(l)]


def _unfold(lines):
    """Rejoin RFC line folding.

    Inside these examples every property line carries the same indent; a
    folded continuation is indented one column further.  Nothing in section
    3.6.5's examples is actually folded, so this is a guard rather than a
    transformation: if a future re-fetch folds a long RRULE, the parse must not
    silently truncate it.
    """
    out = []
    base = None
    for l in lines:
        if not l.strip():
            out.append(l)
            base = None
            continue
        indent = len(l) - len(l.lstrip())
        if base is not None and indent > base and out:
            out[-1] = out[-1].rstrip() + l.strip()
        else:
            base = indent
            out.append(l)
    return out


def _prose_before(lines, i):
    """The example's own descriptive paragraph, the block of prose above BEGIN."""
    para = []
    k = i - 1
    while k >= 0 and not lines[k].strip():
        k -= 1
    while k >= 0 and lines[k].strip() and not lines[k].strip().startswith("END:"):
        para.append(lines[k].strip())
        k -= 1
    return " ".join(reversed(para))


def _offset(v):
    m = re.fullmatch(r"([+-])(\d{2})(\d{2})(\d{2})?", v.strip())
    if not m:
        raise ValueError("bad UTC offset %r" % v)
    sign = -1 if m.group(1) == "-" else 1
    secs = int(m.group(2)) * 3600 + int(m.group(3)) * 60 + int(m.group(4) or 0)
    return timedelta(seconds=sign * secs)


def _naive(v):
    return datetime.strptime(v.strip(), "%Y%m%dT%H%M%S")


def extract(text=None):
    """Return the VTIMEZONE examples of section 3.6.5 as parsed dicts, in order."""
    lines = _unfold(section_lines(text if text is not None else read_rfc()))
    out = []
    i = 0
    while i < len(lines):
        if lines[i].strip() == "BEGIN:VTIMEZONE":
            j = next(k for k in range(i, len(lines))
                     if lines[k].strip() == "END:VTIMEZONE")
            out.append(_parse(lines[i:j + 1], _prose_before(lines, i), len(out) + 1))
            i = j + 1
        else:
            i += 1
    return out


def _parse(block, prose, index):
    vtz = {"index": index, "prose": prose, "tzid": None, "observances": [],
           "raw": [l.strip() for l in block]}
    cur = None
    for raw in block:
        line = raw.strip()
        name, _, value = line.partition(":")
        name = name.upper()
        if name == "BEGIN" and value in ("STANDARD", "DAYLIGHT"):
            cur = {"kind": value, "dtstart": None, "rrule": None, "rdate": [],
                   "tzoffsetfrom": None, "tzoffsetto": None, "tzname": None,
                   "line": line}
            vtz["observances"].append(cur)
        elif name == "END" and value in ("STANDARD", "DAYLIGHT"):
            cur = None
        elif name == "TZID":
            vtz["tzid"] = value
        elif cur is None:
            continue
        elif name == "DTSTART":
            cur["dtstart"] = _naive(value)
        elif name == "RRULE":
            cur["rrule"] = value
        elif name == "RDATE":
            cur["rdate"].extend(_naive(v) for v in value.split(","))
        elif name == "TZOFFSETFROM":
            cur["tzoffsetfrom"] = _offset(value)
        elif name == "TZOFFSETTO":
            cur["tzoffsetto"] = _offset(value)
        elif name == "TZNAME":
            cur["tzname"] = value
    return vtz


def split_until(rrule):
    """(rule without UNTIL, UNTIL as an aware UTC datetime or None)."""
    kept, until = [], None
    for part in rrule.split(";"):
        if part.upper().startswith("UNTIL="):
            v = part.split("=", 1)[1]
            if not v.endswith("Z"):
                raise ValueError(
                    "RFC 5545 section 3.6.5: a VTIMEZONE UNTIL 'MUST be "
                    "specified in UTC time'; got %r" % v)
            until = _parse_utc(v)
        else:
            kept.append(part)
    return ";".join(kept), until


def _parse_utc(v):
    return datetime.strptime(v[:-1], "%Y%m%dT%H%M%S").replace(tzinfo=timezone.utc)


def onsets(obs, until_year=2040, limit=4000):
    """Onset instants (aware, UTC) for one STANDARD/DAYLIGHT observance.

    Wall-clock expansion from DTSTART, then conversion with TZOFFSETFROM, per
    the section 3.6.5 rule quoted in the module docstring.  RDATE values are
    converted the same way and merged.  UNTIL is compared as an instant.
    """
    if obs["rrule"]:
        rule, until = split_until(obs["rrule"])
        horizon = datetime(until_year, 12, 31)
        wall = naive_expand(rule, obs["dtstart"], horizon=horizon, limit=limit)
    else:
        rule, until, wall = None, None, []
    # DTSTART is itself an onset.  Section 3.6.5: "The onset DATE-TIME values
    # for the observance defined by the time zone sub-component is defined by
    # the 'DTSTART', 'RRULE', and 'RDATE' properties."  The RFC's own first
    # example depends on this -- its 1974 DAYLIGHT observance carries only
    # DTSTART:19740106T020000 and RDATE:19750223T020000, so 1974-01-06 is an
    # onset or it is nowhere.  Where DTSTART is synchronized with the RRULE
    # this is a no-op; where it is not (section 3.6.5's fifth example) it adds
    # an onset the rule does not generate, which is exactly the disagreement
    # `tests/test_vtimezone.py` records.
    wall = [obs["dtstart"]] + wall + list(obs["rdate"])
    out = sorted({w - obs["tzoffsetfrom"] for w in wall})
    out = [d.replace(tzinfo=timezone.utc) for d in out]
    if until is not None:
        out = [d for d in out if d <= until]
    return out


class Resolver:
    """The UTC offset function a VTIMEZONE defines.

    'For a given time zone, there may be multiple unique definitions of the
    observances over a period of time' (section 3.6.5); the observances are
    merged into one ordered list of onsets and the offset at an instant is the
    TZOFFSETTO of the latest onset at or before it.  Before the earliest onset
    the component says nothing, and `utcoffset` returns None rather than
    guessing -- section 3.6.5's second example is explicitly annotated with the
    window outside which it must not be used.
    """

    def __init__(self, vtz, until_year=2040):
        self.vtz = vtz
        self.changes = []
        for obs in vtz["observances"]:
            for t in onsets(obs, until_year=until_year):
                self.changes.append((t, obs["tzoffsetto"], obs["tzname"], obs["kind"]))
        self.changes.sort(key=lambda c: c[0])

    def _at(self, instant):
        prev = None
        for c in self.changes:
            if c[0] <= instant:
                prev = c
            else:
                break
        return prev

    def utcoffset(self, instant):
        c = self._at(instant)
        return None if c is None else c[1]

    def tzname(self, instant):
        c = self._at(instant)
        return None if c is None else c[2]

    @property
    def first_onset(self):
        return self.changes[0][0] if self.changes else None

    def transitions(self, start, end):
        """(instant, offset_before, offset_after) for every change in [start, end)."""
        out = []
        for i, c in enumerate(self.changes):
            if start <= c[0] < end and i > 0:
                before = self.changes[i - 1][1]
                if before != c[1]:
                    out.append((c[0], before, c[1]))
        return out


if __name__ == "__main__":
    for vtz in extract():
        print("--- example %d: TZID=%s, %d observances"
              % (vtz["index"], vtz["tzid"], len(vtz["observances"])))
        print("    %s" % vtz["prose"][:160])
        r = Resolver(vtz)
        print("    %d onsets, first %s" % (len(r.changes), r.first_onset))
